<?php 
// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<?php
return ['project-id-version'=>'Elementor Dynamic Blog Grid & Filters','report-msgid-bugs-to'=>'','pot-creation-date'=>'2026-01-19 06:09+0000','po-revision-date'=>'2026-01-19 06:17+0000','last-translator'=>'','language-team'=>'Bengali (Bangladesh)','language'=>'bn_BD','plural-forms'=>'nplurals=2; plural=n != 1;','mime-version'=>'1.0','content-type'=>'text/plain; charset=UTF-8','content-transfer-encoding'=>'8bit','x-generator'=>'Loco https://localise.biz/','x-loco-version'=>'2.8.1; wp-6.9; php-8.2.12','x-domain'=>'dbgfe','messages'=>['An Elementor addon to create dynamic, filterable blog grids with category & tag filters, pagination, and mobile off-canvas UI.'=>'বিভাগ এবং ট্যাগ ফিল্টার, পৃষ্ঠাঙ্কন এবং মোবাইল অফ-ক্যানভাস UI সহ গতিশীল, ফিল্টারযোগ্য ব্লগ গ্রিড তৈরি করার জন্য একটি এলিমেন্টর অ্যাডঅন।','Category'=>'শ্রেণী','Color Template'=>'রঙিন টেমপ্লেট','Columns'=>'কলাম','Content'=>'বিষয়বস্তু','Docs & FAQs'=>'ডক্স এবং প্রায়শই জিজ্ঞাসিত প্রশ্নাবলী','Dynamic Blog Grid'=>'ডায়নামিক ব্লগ গ্রিড','Dynamic Blog Grid & Filters requires Elementor to be installed and activated.'=>'ডায়নামিক ব্লগ গ্রিড এবং ফিল্টারের জন্য এলিমেন্টর ইনস্টল এবং সক্রিয় করা প্রয়োজন।','Elementor Dynamic Blog Grid & Filters'=>'এলিমেন্টর ডায়নামিক ব্লগ গ্রিড এবং ফিল্টার','Enable Category Filter'=>'বিভাগ ফিল্টার সক্ষম করুন','Enable Sidebar'=>'সাইডবার সক্রিয় করুন','Enable Tags Filter'=>'ট্যাগ ফিল্টার সক্ষম করুন','Grid'=>'গ্রিড','Grid Gap (px)'=>'গ্রিড গ্যাপ (পিক্সেল)','Image not found'=>'ছবি পাওয়া যায়নি','No'=>'না','No posts found.'=>'কোন পোস্ট পাওয়া যায়নি.','Posts Per Page'=>'পৃষ্ঠা প্রতি পোস্ট','Read More →'=>'আরও পড়ুন →','Search category'=>'অনুসন্ধান বিভাগ','Search tag'=>'অনুসন্ধান ট্যাগ','Tags'=>'ট্যাগ','Taxonomy Hover'=>'শ্রেণীবিন্যাস হোভার','Video Tutorials'=>'ভিডিও টিউটোরিয়াল','Yes'=>'হ্যাঁ']];
